version: '3'

services:
  pycontw-2022-frontend:
    container_name: pycontw-2022-frontend
    restart: always
    build:
      context: .

networks:
    default:
        external:
            name: pycontw-net
