name: Test, build, deploy

on:
    push:
        branches:
            - main

jobs:
    cd:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            -   name: Checkout 🛎
                uses: actions/checkout@master

            -   name: Setup node env 🏗
                uses: actions/setup-node@v2.1.2
                with:
                    node-version: ${{ matrix.node }}

            -   name: Install dependencies 👨🏻‍💻
                run: npm ci

            -   name: Run linter 👀
                run: npm run lint

            -   name: Run tests 🧪
                run: npm run test

            -   name: Build 👷🏽
                run: npm run generate

            -   name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@3.7.1
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: dist
                    CLEAN: true
